### ISSUE TITLE
add more to Comments example

### ISSUE THREAD

**Issue by kllsamui** [jeremydouglass/rosetta_examples_p5#30]
actual example:
https://github.com/jeremydouglass/rosetta_examples_p5/blob/master/examples/Comments/Comments.pde

what i miss is something ( how to call? inline comment )

possibly add like:

```
// comment at end of line
int a = 5; //________________ used for calculate b in draw()

// comment inside a command line
int a = 5 /* was 6 */, b =7; //________________ used in draw()

**Comment by jeremydouglass** [comment]
Yes, good end-of-line example.

Good point about inline comments using the multi-line syntax, although I think maybe we shouldn't teach people to do that -- because of the way that in Java multiline comments break when they are nested, it is really bad style to use them inline -- if you accidentally add another multiline comment around an inline comment then things break in confusing ways.

In other words, I think this is why people usually don't teach that comment form, even though it works. Or we could include it but encourage people not to do it.

```
// comment out a code line
// println("foo");

// comment at the end of a line
println("foo", "bar"); // "baz"

// comment inline -- not recommended style
println("foo", /*"bar",*/ "baz");
```

**Comment by jeremydouglass** [comment]
@kllsamui -- I incorporated your suggestions!
